- name: MariaDB replicas 
  service:
      name: mariadb # required. Name of the service.
      enabled: true # not required. Whether the service should start on boot. B(At least one of state and enabled are required.)
      state: started # not required. choices: reloaded;restarted;started;stopped. C(started)/C(stopped) are idempotent actions that will not run commands unless necessary.  C(restarted) will always bounce the service.  C(reloaded) will always reload. B(At least one of state and enabled are required.) Note that reloaded will start the service if it is not already started, even if your chosen init system wouldn't normally.
